export const ORDER_STATUS = {
  RESERVED: 'RESERVED',
  PENDING_PAY: 'PENDING_PAY',
  PAID: 'PAID',
  PACKING: 'PACKING',
  SHIPPED: 'SHIPPED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  REFUNDED: 'REFUNDED'
} as const;
